#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 2540x1920 --right-of eDP-1
    bspc monitor eDP-1 -d 1 2 3 4 5
    bspc monitor HDMI-1 -d 6 7 8 9 10
else
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Auto start apps
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
bash $HOME/.config/polybar/forest/launch.sh &
setxkbmap pl
